[package]
name = "ceres"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ceres"
path = "src/lib.rs"


[dependencies]
common = { workspace = true }
jupiter = { workspace = true }
callisto = { workspace = true }
mercury = { workspace = true }

anyhow = { workspace = true }
tokio = { workspace = true, features = ["net", "process"] }
tokio-stream = { workspace = true }
axum = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true, features = ["derive"] }
chrono = { workspace = true }
futures = { workspace = true }
bytes = { workspace = true }
async-trait = { workspace = true }
rand = { workspace = true }
sea-orm = { workspace = true }
ring = { workspace = true }
hex = { workspace = true }
sysinfo = "0.33.1"