[package]
name = "chat"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { workspace = true, features = ["full"] }
anyhow = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true, features = ["json"] }
serde_json = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
clap = { workspace = true, features = ["derive"] }
qdrant-client = { workspace = true }
walkdir = { workspace = true }
dagrs = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
dotenv = { workspace = true }
axum = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "macros"] }
rdkafka = { workspace = true, features = ["cmake-build"] }
futures = { workspace = true }