[package]
name = "orion"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true, features = ["macros"] }
tokio = { workspace = true, features = ["rt-multi-thread", "fs", "process"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["v7"] }
futures-util = { workspace = true }
dashmap = { workspace = true }
once_cell = { workspace = true }
dotenvy = { workspace = true }
tokio-tungstenite = { workspace = true , features = ["native-tls"]}
tungstenite = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
