[package]
name = "orion"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "orion"
path = "src/main.rs"


[dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "fs", "process"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
futures-util = { workspace = true }
once_cell = { workspace = true }
dotenvy = { workspace = true }
tokio-tungstenite = { workspace = true, features = ["native-tls"] }
tungstenite = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls"] }
uuid = { workspace = true, features = ["v4"] }
anyhow = { workspace = true }
itertools = { workspace = true }
parse-display = "0.8.2"
audit = { path = "./audit" }
td_util = { path = "./td_util" }
td_util_buck = { path = "./buck" }
thiserror = { workspace = true }
utoipa.workspace = true
wiremock = "0.6.5"
serial_test = { workspace = true }
tempfile = { workspace = true }
common = { path = "../common" }
