[package]
name = "orion"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true, features = ["macros"] }
tokio = { workspace = true, features = ["rt-multi-thread", "fs", "process"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
futures-util = { workspace = true }
once_cell = { workspace = true }
dotenvy = { workspace = true }
tokio-tungstenite = { workspace = true , features = ["native-tls"]}
tungstenite = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
uuid = { workspace = true, features = ["v4"] }
anyhow = "1.0"
itertools = "0.13.0"
argfile = "0.1.5"
clap = {version = "4.1.4"}
equivalent = "1.0.0"
futures = "0.3.30"
parse-display = "0.8.2"
rayon = "1.6.1"
tempfile = "3.1.0"
audit = { path = "./audit" }
td_util = { path = "./td_util" }
td_util_buck = { path = "./buck" }
thiserror = "1.0.36"
utoipa-axum.workspace = true
utoipa.workspace = true
utoipa-swagger-ui = { workspace = true, features = ["axum"] }
wiremock = "0.6.5"
serial_test = "3.2.0"