[package]
name = "mega"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "gateway", "git", "common", "database", "p2p", "kvcache", "sync"]
exclude = ["craft", "mda"]

[dependencies]
gateway = { path = "gateway" }
common = { path = "common" }
p2p = { path = "p2p" }
mda = {path = "mda"}
config = "0.13.3"
serde_json = "1.0.105"
anyhow = "1.0.75"
lazy_static = "1.4.0"
shadow-rs = "0.23.0"
dotenvy = "0.15.7"
tracing-subscriber = "0.3.17"
thiserror = "1.0.47"
pgp = "0.9.0"
rand = "0.8.5"
smallvec = "1.10.0"
tokio = { version = "1.32.0", features = ["full"] }
clap = { version = "4.4.0", features = ["derive"] }
serde = { version = "1.0.188", features = ["derive"] }

[build-dependencies]
shadow-rs = "0.23.0"
