[workspace]
members = [
    "mono",
    "mega",
    "gateway",
    "common",
    "mercury",
    "jupiter",
    "ceres",
    "libra",
    "vault",
    "neptune",
    "aries",
    "saturn",
    "taurus",
    "lunar/src-tauri",
    "atlas",
    "panel",
]
default-members = ["mega", "mono", "libra", "aries"]
resolver = "1"

[workspace.dependencies]
gateway = { path = "gateway" }
common = { path = "common" }
mercury = { path = "mercury" }
jupiter = { path = "jupiter" }
ceres = { path = "ceres" }
callisto = { path = "jupiter/callisto" }
gemini = { path = "gemini" }
vault = { path = "vault" }
neptune = { path = "neptune" }
saturn = { path = "saturn" }
taurus = { path = "taurus" }
mega = { path = "mega" }
mono = { path = "mono" }
libra = { path = "libra" }

anyhow = "1.0.93"
serde = "1.0.215"
serde_json = "1.0.132"
tracing = "0.1.40"
tracing-subscriber = "0.3.19"
tracing-appender = "0.2"
thiserror = "2.0.6"
rand = "0.8.5"
smallvec = "1.13.2"
tokio = "1.42"
tokio-stream = "0.1.17"
tokio-test = "0.4.4"
clap = "4.5.23"
async-trait = "0.1.83"
async-stream = "0.3.6"
bytes = "1.8.0"
memchr = "2.7.4"
chrono = "0.4.39"
sha1 = "0.10.6"
futures = "0.3.30"
futures-util = "0.3.30"
go-defer = "0.1.0"
russh = "0.49.0"
russh-keys = "0.49.0"
axum = "0.7.7"
axum-extra = "0.9.4"
axum-server = "0.7.1"
tower-http = "0.6.1"
tower = "0.5.1"
hex = "0.4.3"
sea-orm = "1.1.1"
flate2 = "1.0.35"
bstr = "1.11.0"
colored = "2.1.0"
idgenerator = "2.0.0"
num_cpus = "1.16.0"
config = "0.14.1"
shadow-rs = "0.36.0"
reqwest = "0.12.9"
lazy_static = "1.5.0"
uuid = "1.11.0"
regex = "1.11.1"
ed25519-dalek = "2.1.1"
ctrlc = "3.4.4"
git2 = "0.19.0"
tempfile = "3.14.0"
home = "0.5.9"
ring = "0.17.8"
cedar-policy = "4.2.2"
secp256k1 = "0.30.0"
oauth2 = "4.4.2"
base64 = "0.22.1"

[profile.release]
debug = true