[package]
name = "mega"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".","gateway", "git", "common", "database"]

[dependencies]
gateway = { path = "gateway" }
common = { path = "common" }

config = "0.13.3"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
clap = { version = "4.3.10", features = ["derive"] }
anyhow = "1.0.69"
lazy_static = "1.4.0"
shadow-rs = "0.23.0"
tokio = {version = "1.28.1", features = ["full"]}
dotenvy = "0.15.7"
tracing-subscriber = "0.3.17"
russh = "0.37.1"
russh-keys = "0.37.1"
thiserror = "1.0.40"

[build-dependencies]
shadow-rs = "0.23.0"
