[workspace]
members = [
    "mega",
    "gateway",
    "common",
    "mercury",
    "jupiter",
    "venus",
    "ceres",
    "libra",
    "vault",
]
exclude = ["craft"]
resolver = "1"

[workspace.dependencies]
gateway = { path = "gateway" }
common = { path = "common" }
mercury = { path = "mercury" }
jupiter = { path = "jupiter" }
venus = { path = "venus" }
ceres = { path = "ceres" }
callisto = { path = "jupiter/callisto" }
gemini = { path = "gemini" }
vault = { path = "vault" }

anyhow = "1.0.86"
serde = "1.0.203"
serde_json = "1.0.117"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-appender = "0.2"
thiserror = "1.0.61"
rand = "0.8.5"
smallvec = "1.13.2"
tokio = "1.38.0"
tokio-stream = "0.1.15"
tokio-test = "0.4.4"
rayon = "1.10.0"
clap = "4.5.4"
async-trait = "0.1.80"
async-stream = "0.3.5"
bytes = "1.6.0"
memchr = "2.7.2"
chrono = "0.4.38"
sha1 = "0.10.6"
sha256 = "1.5"
futures = "0.3.30"
futures-util = "0.3.30"
go-defer = "0.1.0"
russh = "0.43.0"
russh-keys = "0.43.0"
axum = "0.7.5"
tower-http = "0.5.2"
tower = "0.4.13"
hex = "0.4.3"
sea-orm = "0.12.15"
flate2 = "1.0.30"
bstr = "1.9.1"
colored = "2.1.0"
idgenerator = "2.0.0"
num_cpus = "1.16.0"
config = "0.14.0"
shadow-rs = "0.29.0"
reqwest = "0.12.5"
