[workspace]
members = [
  "mono",
  "common",
  "jupiter",
  "ceres",
  "vault",
  "saturn",
  "orion",
  "orion-server",
  "extensions/rag/chat",
  "extensions/rag/index",
  "extensions/observatory",
  "context",
  "scorpio",
]
default-members = ["mono", "orion", "orion-server"]
resolver = "1"


[workspace.dependencies]
mono = { path = "mono" }
common = { path = "common" }
jupiter = { path = "jupiter" }
ceres = { path = "ceres" }
callisto = { path = "jupiter/callisto" }
vault = { path = "vault" }
saturn = { path = "saturn" }
observatory = { path = "extensions/observatory" }
orion = { path = "orion" }
bellatrix = { path = "orion-server/bellatrix" }
context = { path = "context" }

git-internal = "0.4.0"
libvault-core = "0.1.0"

#====
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_urlencoded = "0.7"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
tracing-appender = "0.2.4"
thiserror = "2.0.17"
clap = "4.5.54"

#====
tokio = "1.49.0"
tokio-stream = "0.1.18"
tokio-util = "0.7.18"
async-trait = "0.1.89"
async-stream = "0.3.6"
async-recursion = "1.1.1"
futures = "0.3.31"
futures-util = "0.3.31"
axum = { version = "0.8.8", features = ["macros", "json"] }
axum-extra = "0.12.3"
russh = "0.56.0"
tower-http = "0.6.8"
tower = "0.5.3"
tower-sessions = { version = "0.14", features = ["memory-store"] }
time = { version = "0.3.45", features = ["serde"] }

#====
sea-orm = "1.1.19"
sea-orm-migration = "1.1.19"

#====
rand = "0.9.2"
rand_chacha = "0.9.0"
flate2 = "1.1.8"
smallvec = "1.15.1"
bytes = "1.11"
chrono = { version = "0.4.42", features = ["serde"] }
sha1 = "0.10.6"
hex = "0.4.3"

idgenerator = "2.0.0"
config = "0.15.19"
reqwest = "0.13.1" 
lazy_static = "1.5.0"
uuid = "1.19.0"
regex = "1.12.2"
ed25519-dalek = "2.2.0"
ctrlc = "3.5.1"
ring = "0.17.14"
cedar-policy = "4.8.2"
secp256k1 = "0.30.0"
pgp = "0.15.0"
openssl = "0.10.75"
oauth2 = "5.0.0"
base64 = "0.22.1"
aws-config = "1.8.12"
aws-sdk-s3 = "1.119"

utoipa = { version = "5.4.0", features = ["chrono"] }
utoipa-axum = "0.2.0"
utoipa-swagger-ui = "9.0.2"
tempfile = "3.24.0"
rdkafka = "0.38.0"
dashmap = "6.1.0"
once_cell = "1.21.3"
testcontainers = "0.26"
scopeguard = "1.2.0"
serial_test = "3.3.1"
sysinfo = "0.37"
http = "1.4.0"
http-body = "1.0.1"
http-body-util = "0.1.3"
infer = "0.19.0"
path-absolutize = "3.1.1"
url = "2.5.8"
jemallocator = "0.5.4"
mimalloc = "0.1.48"
assert_cmd = "2.1.2"
dotenvy = "0.15.7"
tokio-tungstenite = "0.28"
tungstenite = "0.28"
itertools = "0.14.0"
bs58 = "0.5.1"
syn = "2.0.114"
quote = "1.0.43"
proc-macro2 = "1.0.105"
log = "0.4.29"
env_logger = "0.11.8"
qdrant-client = "1.16"
walkdir = "2.5"
dagrs = "0.5.2"
tar = "0.4"
indexmap = "2.13"
envsubst = "0.2.1"
diffs = "0.5.1"
directories = "6.0.0"
dotenv = "0.15"
redis = "1.0.2"
redis-test = "1.0.1"
bincode = "2.0.1"
rustls = "0.23.36"

[profile.release]
debug = true
