[workspace]
members = [
    "mono",
    "mega",
    "gateway",
    "common",
    "mercury",
    "jupiter",
    "jupiter/migration",
    "ceres",
    "libra",
    "vault",
    "aries",
    "saturn",
    "orion",
    "orion-server",
    "third-party",
    "extensions/rag/chat",
    "extensions/rag/index",
    "extensions/observatory",
    "scorpio",
]
default-members = ["mega", "mono", "libra", "aries", "orion", "orion-server"]
resolver = "1"

[workspace.dependencies]
gateway = { path = "gateway" }
common = { path = "common" }
mercury = { path = "mercury" }
jupiter = { path = "jupiter" }
ceres = { path = "ceres" }
callisto = { path = "jupiter/callisto" }
migration = { path = "jupiter/migration" }
gemini = { path = "gemini" }
vault = { path = "vault" }
saturn = { path = "saturn" }
mono = { path = "mono" }
observatory = { path = "extensions/observatory" }
orion = { path = "orion" }

anyhow = "1.0.98"
serde = "1.0.219"
serde_json = "1.0.140"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tracing-appender = "0.2.3"
thiserror = "2.0.12"
rand = "0.9.1"
rand_chacha = "0.9.0"
smallvec = "1.15.0"
tokio = "1.45.1"
tokio-stream = "0.1.17"
tokio-test = "0.4.4"
tokio-util = "0.7.15"
clap = "4.5.39"
async-std = "1.13.1"
async-trait = "0.1.88"
async-stream = "0.3.6"
bytes = "1.10.1"
memchr = "2.7.4"
chrono = "0.4.41"
sha1 = "0.10.6"
futures = "0.3.31"
futures-util = "0.3.31"
go-defer = "0.1.0"
russh = "0.52.1"
axum = "0.8.4"
axum-extra = "0.10.1"
tower-http = "0.6.4"
tower = "0.5.2"
hex = "0.4.3"
sea-orm = "1.1.12"
sea-orm-migration = "1.1.12"
flate2 = "1.1.1"
bstr = "1.12.0"
colored = "3.0.0"
idgenerator = "2.0.0"
num_cpus = "1.17.0"
config = "0.15.11"
reqwest = "0.12.18"
lazy_static = "1.5.0"
uuid = "1.17.0"
regex = "1.11.1"
ed25519-dalek = "2.1.1"
ctrlc = "3.4.7"
git2 = "0.20.2"
home = "0.5.11"
ring = "0.17.14"
cedar-policy = "4.4.1"
secp256k1 = "0.30.0"
pgp = "0.15.0"
openssl = "0.10.73"
oauth2 = "5.0.0"
base64 = "0.22.1"
encoding_rs = "0.8.35"
aws-config = "1.6.3"
aws-sdk-s3 = "1.90.0"
quinn = "0.11.8"
utoipa = "5.3.1"
utoipa-axum = "0.2.0"
utoipa-swagger-ui = "9.0.2"
tempfile = "3.20.0"
rdkafka = "0.37.0"
threadpool = "1.8.1"
lru-mem = "0.3.0"
dashmap = "6.1.0"
rayon = "1.10.0"
byteorder = "1.5.0"
bincode = "2.0.1"
once_cell = "1.21.3"
testcontainers = "0.24.0"
scopeguard = "1.2.0"
serial_test = "3.2.0"
sysinfo = "0.35.1"
http = "1.3.1"
byte-unit = "5.1.6"
color-backtrace = "0.7.0"
ignore = "0.4.23"
imara-diff = "0.1.8"
indicatif = "0.17.11"
infer = "0.19.0"
path-absolutize = "3.1.1"
pathdiff = "0.2.3"
rpassword = "7.4.0"
similar = "2.7.0"
url = "2.5.4"
wax = "0.6.0"
pager = "0.16.1"
tracing-test = "0.2.5"
jemallocator = "0.5.4"
mimalloc = "0.1.46"
assert_cmd = "2.0.17"
async-session = "3.0.0"
dotenvy = "0.15.7"
tokio-tungstenite = "0.26.2"
tungstenite = "0.26.2"
itertools = "0.14.0"
rusty_vault = "0.2.1"
bs58 = "0.5.1"
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
log = "0.4.27"
env_logger = "0.11.7"
qdrant-client = "1.7"
walkdir = "2.4"
dagrs = "0.4.4"
tar = "0.4"

envsubst = "0.2.1"
rcgen = "0.13.2"
diffs = "0.5.1"
libc = "0.2.172"
zstd-sys = "2.0.15+zstd.1.5.7"
quickcheck = "1.0.3"
directories = "6.0.0"

[profile.release]
debug = true
