[workspace]
members = [
    "mono",
    "mega",
    "gateway",
    "common",
    "mercury",
    "jupiter",
    "jupiter/migration",
    "ceres",
    "libra",
    "vault",
    "aries",
    "saturn",
    "orion",
    "orion-server",
    "third-party",
    "observatory",
]
default-members = ["mega", "mono", "libra", "aries", "orion-server"]
resolver = "1"

[workspace.dependencies]
gateway = { path = "gateway" }
common = { path = "common" }
mercury = { path = "mercury" }
jupiter = { path = "jupiter" }
ceres = { path = "ceres" }
callisto = { path = "jupiter/callisto" }
migration = { path = "jupiter/migration" }
gemini = { path = "gemini" }
vault = { path = "vault" }
saturn = { path = "saturn" }
mega = { path = "mega" }
mono = { path = "mono" }
libra = { path = "libra" }
observatory = { path = "observatory" }
orion = { path = "orion" }
orion-server = { path = "orion-server" }
third-party = { path = "third-party" }

anyhow = "1.0.93"
serde = "1.0.215"
serde_json = "1.0.138"
tracing = "0.1.40"
tracing-subscriber = "0.3.19"
tracing-appender = "0.2"
thiserror = "2.0.11"
rand = "0.9.0"
smallvec = "1.13.2"
tokio = "1.42"
tokio-stream = "0.1.17"
tokio-test = "0.4.4"
clap = "4.5.28"
async-trait = "0.1.86"
async-stream = "0.3.6"
bytes = "1.10.0"
memchr = "2.7.4"
chrono = "0.4.39"
sha1 = "0.10.6"
futures = "0.3.30"
futures-util = "0.3.30"
go-defer = "0.1.0"
russh = "0.52"
axum = "0.8.4"
axum-extra = "0.10.1"
tower-http = "0.6.1"
tower = "0.5.2"
hex = "0.4.3"
sea-orm = "1.1.10"
flate2 = "1.0.35"
bstr = "1.11.3"
colored = "3.0.0"
idgenerator = "2.0.0"
num_cpus = "1.16.0"
config = "0.15.7"
reqwest = "0.12.12"
lazy_static = "1.5.0"
uuid = "1.13.1"
regex = "1.11.1"
ed25519-dalek = "2.1.1"
ctrlc = "3.4.4"
git2 = "0.20.0"
tempfile = "3.19.0"
home = "0.5.9"
ring = "0.17.8"
cedar-policy = "4.3.1"
secp256k1 = "0.30"
pgp = "0.15"
async-std = "1.13"
openssl = "0.10"
oauth2 = "5.0.0"
base64 = "0.22.1"
encoding_rs = "0.8.31"
aws-config = "1.6.0"
aws-sdk-s3 = "1.79.0"
quinn = "0.11"
utoipa = "5.3"
rdkafka = "0.37"
threadpool = "1.8.1"
lru-mem = "0.3.0"
dashmap = "6.1"
rayon = "1.10.0"
byteorder = "1.5.0"
bincode = "2.0"
once_cell = "1.21"
testcontainers = "0.23"
scopeguard = "1.2.0"
serial_test = "3.2.0"
sysinfo = "0.35.0"
tokio-util = "0.7.13"
http = "1.3.1"
byte-unit = "5.1.4"
color-backtrace = "0.7.0"
ignore = "0.4.23"
imara-diff = "0.1.7"
indicatif = "0.17.8"
infer = "0.19.0"
path-absolutize = "3.1.1"
pathdiff = "0.2.1"
rpassword = "7.3.1"
similar = "2.6.0"
url = "2.5.3"
wax = "0.6.0"
pager = "0.16.0"
tracing-test = "0.2.4"
jemallocator = "0.5.4"
mimalloc = "0.1.43"
assert_cmd = "2.0.16"
async-session = "3.0.0"
dotenvy = "0.15.7"
tokio-tungstenite = "0.26.2"
tungstenite = "0.26.2"
itertools = "0.14.0"
rusty_vault = "0.2.1"
bs58 = "0.5.1"

[profile.release]
debug = true
