[workspace]
members = [
    "mono",
    "mega",
    "gateway",
    "common",
    "mercury",
    "jupiter",
    "ceres",
    "libra",
    "vault",
    "neptune",
    "aries",
    "saturn",
    "taurus",
    "lunar/src-tauri",
    "atlas",
]
default-members = ["mega", "mono", "libra", "aries"]
resolver = "1"

[workspace.dependencies]
gateway = { path = "gateway" }
common = { path = "common" }
mercury = { path = "mercury" }
jupiter = { path = "jupiter" }
ceres = { path = "ceres" }
callisto = { path = "jupiter/callisto" }
gemini = { path = "gemini" }
vault = { path = "vault" }
neptune = { path = "neptune" }
saturn = { path = "saturn" }
taurus = { path = "taurus" }
mega = { path = "mega" }
mono = { path = "mono" }
libra = { path = "libra" }

anyhow = "1.0.87"
serde = "1.0.210"
serde_json = "1.0.128"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-appender = "0.2"
thiserror = "1.0.63"
rand = "0.8.5"
smallvec = "1.13.2"
tokio = "1.40.0"
tokio-stream = "0.1.16"
tokio-test = "0.4.4"
clap = "4.5.17"
async-trait = "0.1.82"
async-stream = "0.3.5"
bytes = "1.7.1"
memchr = "2.7.4"
chrono = "0.4.38"
sha1 = "0.10.6"
sha256 = "1.5"
futures = "0.3.30"
futures-util = "0.3.30"
go-defer = "0.1.0"
russh = "0.45.0"
russh-keys = "0.45.0"
axum = "0.7.5"
axum-extra = "0.9.3"
axum-server = "0.7"
tower-http = "0.5.2"
tower = "0.5.1"
hex = "0.4.3"
sea-orm = "1.0.1"
flate2 = "1.0.30"
bstr = "1.10.0"
colored = "2.1.0"
idgenerator = "2.0.0"
num_cpus = "1.16.0"
config = "0.14.0"
shadow-rs = "0.34.0"
reqwest = "0.12.7"
lazy_static = "1.5.0"
uuid = "1.10.0"
regex = "1.10.4"
ed25519-dalek = "2.1.1"
ctrlc = "3.4.4"
git2 = "0.19.0"
tempfile = "3.10.1"
home = "0.5.9"
