[package]
name = "mercury"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
callisto = { path = "../jupiter/callisto" }
venus = { path = "../venus" }
delta = { path = "../delta" }
serde = { workspace = true, features = ["derive"] }
bstr = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
flate2 = { workspace = true, features = ["zlib"] } # enable linking against the libz(C lib); better performance
tracing = { workspace = true }
sha1 = { workspace = true }
colored = { workspace = true }
chrono = { workspace = true }
threadpool = "1.8.1"
num_cpus = "1.16.0"
dashmap = "5.5.3"
tokio.workspace = true
lru-mem = "0.3.0"
bincode = "1.3.3"
uuid = { version = "1.7.0", features = ["v4"]}
mimalloc = "0.1.39" # avoid sticking on dropping
rayon =  "1.9.0"
byteorder = "1.5.0"