[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "gateway"
path = "src/mod.rs"


[dependencies]
git = {path = "../git"}
common = {path = "../common"}
database = {path = "../database"}
entity = { path = "../database/entity" }
sync = { path = "../sync"}
anyhow = "1.0.75"
axum = "0.6.20"
hyper = "0.14.27"
regex = "1.9.1"
tracing = "0.1.37"
russh = "0.37.1"
russh-keys = "0.37.1"
ed25519-dalek = "1.0.1"
serde = "1.0.188"
serde_json = "1.0.105"
tower = "0.4.13"
clap = { version = "4.4.0", features = ["derive"] }
tower-http = {version = "0.4.3", features = ["cors"]}
tokio = {version = "1.32", features = ["full"]}
chrono = "0.4.26"
octocrab = "0.29.3"
jsonwebtoken = "8.3.0"