[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "gateway"
path = "src/mod.rs"


[dependencies]
git = {path = "../git"}
database = {path = "../database"}
anyhow = "1.0.71"
axum = "0.6.18"
clap = { version = "4.3.0", features = ["derive"] }
hyper = "0.14.26"
regex = "1.9.1"
serde = "1.0.164"
tokio = {version = "1.29.1", features = ["full"]}
tracing = "0.1.37"
russh = "0.37.1"
russh-keys = "0.37.1"
ed25519-dalek = "1.0.1"
serde_json = "1.0.103"
tower = "0.4.13"
tower-http = {version = "0.4.3", features = ["cors"]}

