[package]
name = "git-craft"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
anyhow = "1.0.75"
pgp = "0.10.2"
rand = "0.8.5"
smallvec = "1.10.0"
clap = { version = "4.4.0", features = ["derive"] }

