[package]
name = "api-model"
version = "0.1.0"
edition.workspace = true


[lib]
name = "api_model"
path = "src/lib.rs"


[dependencies]
serde = { workspace = true, features = ["derive"] }
utoipa = { workspace = true }
