[package]
name = "mega-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# name = "mega-core"
path = "src/mod.rs"

[dependencies]
anyhow = "1.0.71"
clap = "4.2.7"
thiserror = "1.0.40"
