[package]
name = "context"
version = "0.1.0"
edition.workspace = true

[lib]
name = "context"
path = "src/lib.rs"

[features]
default = []

[dependencies]
common = { workspace = true }
jupiter = { workspace = true }
vault = { workspace = true }
redis = { workspace = true }
