[package]
name = "bellatrix"
version = "0.1.0"
edition.workspace = true

[lib]
name = "bellatrix"
path = "src/lib.rs"

[dependencies]
api-model = { workspace = true }
common = { workspace = true }
reqwest = { workspace = true, features = ["json"]}
anyhow = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }