[package]
name = "get_cve_id"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15"
rdkafka = "0.37"
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.13"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tokio-postgres = "0.7.13"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
