[package]
name = "simple-bellatrix"
version = "0.1.0"
edition = "2024"

[lib]
name = "simple_bellatrix"
path = "src/lib.rs"

[dependencies]
reqwest = { workspace = true, features = ["json"]}
anyhow = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }