[package]
name = "vault"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty_vault = "0.2.1"
serde_json = "1.0.117"
go-defer = "0.1.0"
openssl = "0.10.64"
hex = "0.4.3"
lazy_static = "1.5.0"
bs58 = "0.5.1"
serde = { version = "1.0.117", features = ["derive"] }
secp256k1 = { workspace = true , features = ["serde", "rand","hashes"] }
tokio = {workspace = true, features = ["full"]}
