[package]
name = "vault"
version = "0.1.0"
edition.workspace = true

[lib]
name = "vault"
path = "src/lib.rs"

[dependencies]
jupiter = { workspace = true }
common = { workspace = true }

tracing = { workspace = true }
serde_json = { workspace = true }
openssl = { version = "0.10.75" }
hex = { workspace = true }
bs58 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
secp256k1 = { workspace = true, features = ["serde", "rand", "hashes"] }
tokio = { workspace = true, features = ["full"] }
pgp = { workspace = true }
smallvec = { workspace = true }
libvault-core = { workspace = true }
async-trait = { workspace = true }


[dev-dependencies]
tempfile = { workspace = true }
rand = { workspace = true }
