[package]
name = "vault"
version = "0.1.0"
edition = "2024"

[dependencies]
jupiter = { workspace = true }
common = { workspace = true}

tracing = { workspace = true }
serde_json = { workspace = true }
go-defer = { workspace = true }
openssl = { workspace = true }
hex = { workspace = true }
bs58 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
secp256k1 = { workspace = true, features = ["serde", "rand", "hashes"] }
tokio = { workspace = true, features = ["full"] }
pgp = { workspace = true }
smallvec = { workspace = true }

[dependencies.rusty_vault]
git = "https://github.com/Tongsuo-Project/RustyVault"
tag = "v0.2.2"
features = ["sync_handler"]
