[package]
name = "vault"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { workspace = true}
jupiter = { workspace = true }

rusty_vault = { workspace = true }
serde_json = { workspace = true }
go-defer = { workspace = true }
openssl = { workspace = true }
hex = { workspace = true }
lazy_static = { workspace = true }
bs58 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
secp256k1 = { workspace = true, features = ["serde", "rand", "hashes"] }
tokio = { workspace = true, features = ["full"] }
async-std = { workspace = true }
pgp = { workspace = true }
smallvec = { workspace = true }
