[package]
name = "scorpio"
version = "0.1.0"
edition = "2021"


[lib]
name = "scorpio"
path = "src/lib.rs"


[dependencies]
api-model = { path = "../api-model" }
git-internal = { workspace = true }
reqwest = { workspace = true, features = ["json", "blocking"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
axum = { workspace = true, features = ["macros"] }
rfuse3 = {  version = "0.0.7", features = ["tokio-runtime", "unprivileged"] }
clap = { workspace = true, features = ["derive"] }

toml = { workspace = true }
libc = "0.2.180"
log = { workspace = true }
radix_trie = "0.3.0"
tracing = { workspace = true }
serde_json = { workspace = true }
once_cell = { workspace = true }
env_logger = { workspace = true }
sled = "0.34.7"
bincode = { workspace = true }
async-recursion = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
libfuse-fs = { version = "0.1.11"}
whoami = "1.6.0"
thiserror = { workspace = true }
crossbeam = "0.8.4"
dashmap = { workspace = true }
ring = "0.17.14"
hex = { workspace = true }

async-trait.workspace = true
tracing-subscriber.workspace = true


[features]
async-io = []

[dev-dependencies]
tempfile = { workspace = true }
serial_test = { workspace = true }
lazy_static = { workspace = true }
assert_cmd = { workspace = true }
scopeguard = { workspace = true }
testcontainers = { workspace = true, features = [
    "http_wait",
    "reusable-containers",
] }
reqwest = { workspace = true, features = ["blocking"] }
http = { workspace = true }
tower = "0.5"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
