[package]
name = "scorpio"
version = "0.1.0"
edition = "2021"

[dependencies]
libra = { path = "../libra" }
mercury = { path = "../mercury" }
ceres = { path = "../ceres" }

clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
vm-memory = { version = "0.15.0", features = ["backend-mmap", "backend-bitmap"] }
axum = { version =  "0.7.7",features=["macros"]}
fuse3 = { version = "0.8.1" ,features = ["tokio-runtime","unprivileged"]}
futures-util = { version = "0.3.30", features = ["sink"] }
syn = { version = "2.0.98", features = ["full", "extra-traits"] }

futures = "0.3.31"
vmm-sys-util = "0.11"
quote = "1.0.38"
proc-macro2 = "1.0.93"
uuid = "1.14.0"
libfuse-fs = "0.1.1"
regex = "1.11.1"
whoami = "1.6.0"
wax = "0.6.0"
ignore = "0.4.23"
url = "2.5.4"
walkdir = "2.5.0"
fjall = "2.8.0"
thiserror = "2.0.12"
env_logger = "0.11.5"
sled = "0.34.7"
bincode = "1.3.3"
async-recursion = "1.1.1"
bytes = "1.7.2"
crossbeam = "0.8.4"
fs_extra = "1.2"
toml = "0.8.19"
libc = "0.2.158"
log = "0.4.22"
radix_trie = "0.2.1"
signal-hook = "0.3.17"
tracing = "0.1.40"
serde_json = "1.0.128"
once_cell = "1.19.0"
arc-swap = "1.7.1"

[features] 
async-io = []

[workspace]

[package.metadata.docs.rs]
all-features = true
targets = [
    "x86_64-unknown-linux-gnu",
]
