[package]
name = "scorpio"
version = "0.1.0"
edition = "2021"

[dependencies]
libra = { path = "../libra" }
mercury = { path = "../mercury" }
ceres = { path = "../ceres" }
toml = "0.8.19"
libc = "0.2.158"
log = "0.4.22"
radix_trie = "0.2.1"
signal-hook = "0.3.17"
tracing = "0.1.40"
serde_json = "1.0.128"
once_cell = "1.19.0"
arc-swap = "1.7.1"
reqwest =  { version = "0.12.7", features = ["json","blocking"] }
serde = { version = "1.0.210", features = ["derive"] }
fuse-backend-rs = { version = "0.12.0", features = ["fusedev","async-io"]}
tokio = { version = "1.40.0", features = ["full"] }
vm-memory = { version = "0.15.0", features = ["backend-mmap", "backend-bitmap"] }
env_logger = "0.11.5"
sled = "0.34.7"
bincode = "1.3.3"
async-recursion = "1.1.1"
bytes = "1.7.2"
axum = { version =  "0.7.7",features=["macros"]}
futures = "0.3.31"
fuse3 = { version = "0.8.1" ,features = ["tokio-runtime","unprivileged"]}
vmm-sys-util = { version = "0.11" }
futures-util = { version = "0.3.30", features = ["sink"] }
quote = "1.0.38"
proc-macro2 = "1.0.93"
syn = { version = "2.0.98", features = ["full", "extra-traits"] }
uuid = "1.14.0"
libfuse-fs = "0.1.0"
regex = "1.11.1"


[features] 
async-io = []

[workspace]


[package.metadata.docs.rs]
all-features = true
targets = [
    "x86_64-unknown-linux-gnu",
]
