lfs_url = "http://git.gitmega.com"
store_path = "/tmp/scorpio-megadir/store"
config_file = "config.toml"
git_author = "MEGA"
git_email = "admin@mega.org"
workspace = "/tmp/scorpio-megadir/mount"
base_url = "http://git.gitmega.com"
dicfuse_readable = "true"
load_dir_depth = "3"
fetch_file_thread = "10"
dicfuse_import_concurrency = "4"
dicfuse_dir_sync_ttl_secs = "5"
dicfuse_stat_mode = "accurate"
dicfuse_open_buff_max_bytes = "268435456"
dicfuse_open_buff_max_files = "4096"
antares_load_dir_depth = "0"
antares_dicfuse_stat_mode = "fast"
antares_dicfuse_open_buff_max_bytes = "67108864"
antares_dicfuse_open_buff_max_files = "1024"
antares_dicfuse_dir_sync_ttl_secs = "5"
antares_upper_root = "/tmp/scorpio-megadir/antares/upper"
antares_cl_root = "/tmp/scorpio-megadir/antares/cl"
antares_mount_root = "/tmp/scorpio-megadir/antares/mnt"
antares_state_file = "/tmp/scorpio-megadir/antares/state.toml"
