lfs_url = "http://git.gitmega.com"
store_path = "/tmp/megadir/store"
config_file = "config.toml"
git_author = "MEGA"
git_email = "admin@mega.org"
workspace = "/tmp/megadir/mount"
base_url = "http://git.gitmega.com"
dicfuse_readable = "true"
load_dir_depth = "4"
fetch_file_thread = "10"
