[package]
name = "index"
version = "0.1.0"
edition = "2021"

[lib]
name = "index"
path = "src/lib.rs"

[dependencies]
syn = { workspace = true, features = ["full"] }
anyhow = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true, features = ["json"] }
serde_json = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
clap = { workspace = true, features = ["derive"] }
qdrant-client = { workspace = true }
walkdir = { workspace = true }
tokio-stream = { version = "0.1", features = ["full"] }
dagrs = { workspace = true }
observatory = { path = '../../observatory' }
flate2 = { workspace = true }
tar = { workspace = true }
dotenv = { workspace = true }

