[package]
name = "callisto"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "callisto"
path = "src/mod.rs"

[dependencies]
serde = { workspace = true, features = ["derive"] }
sea-orm = { workspace = true, features = ["sqlx-postgres"] }
chrono = { workspace = true }
idgenerator = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
