[package]
name = "callisto"
version = "0.1.0"
publish = false
edition.workspace = true

[lib]
name = "callisto"
path = "src/mod.rs"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sea-orm = { workspace = true, features = ["sqlx-postgres"] }
chrono = { workspace = true }
idgenerator = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
api-model = { workspace = true }
