[package]
name = "callisto"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "callisto"
path = "src/mod.rs"

[dependencies]
serde = { workspace = true, features = ["derive"] }
sea-orm = { workspace = true, features = ["sqlx-postgres", "sqlx-mysql", "sqlx-sqlite"] }
utoipa = { workspace = true, features = ["axum_extras"] }
chrono = { workspace = true }
idgenerator = { workspace = true }
rand = { workspace = true }
