[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "entity"
path = "src/mod.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
chrono = "0.4.23"

[dependencies.sea-orm]
version = "0.11.3"
