[package]
name = "mono"
version = "0.1.0"
edition = "2021"
authors = ["Quanyi Ma <genedna@gmail.com>"]
keywords = ["git", "monorepo", "decentralized"]
license = "MIT OR Apache-2.0"
readme = "README.md"
build = "src/build.rs"

[[bin]]
name = "mono"
path = "src/main.rs"

[dependencies]
common = { workspace = true }
callisto = { workspace = true }
jupiter = { workspace = true }
ceres = { workspace = true }
taurus = { workspace = true }
vault = { workspace = true }
saturn = { workspace = true }

anyhow = { workspace = true }
axum = { workspace = true }
axum-server = { workspace = true, features = ["tls-rustls"] }
tower = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
russh = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true, features = ["derive"] }
tower-http = { workspace = true, features = [
    "cors",
    "trace",
    "decompression-full",
] }
axum-extra = { workspace = true, features = ["typed-header"] }
tokio = { workspace = true, features = ["net", "macros"] }
tokio-stream = { workspace = true }
async-stream = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
uuid = { workspace = true, features = ["v4"] }
regex = { workspace = true }
ed25519-dalek = { workspace = true, features = ["pkcs8"] }
lazy_static = { workspace = true }
ctrlc = { workspace = true }
shadow-rs = { workspace = true }
oauth2 = { workspace = true }
base64 = { workspace = true }
async-session = "3.0.0"
http = "1.1.0"
cedar-policy = { workspace = true }

[target.'cfg(not(windows))'.dependencies]
jemallocator = "0.5.4"

[target.'cfg(windows)'.dependencies]
mimalloc = "0.1.43"

[dev-dependencies]

[build-dependencies]
shadow-rs = { workspace = true }

# [target.'cfg(not(target_env = "msvc"))'.dependencies]
# tikv-jemallocator = "0.6"

# [target.'cfg(not(target_env = "msvc"))'.dependencies]
# jemallocator = {version = "0.5.4", features = ["debug", "profiling"]}