[package]
name = "cve"
version = "0.1.0"
edition = "2024"

[dependencies]
data_transporter = {workspace = true}

dotenvy = "0.15"
rdkafka = "0.37"
regex = "1.11"
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.24"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tokio-postgres = "0.7.13"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }