apiVersion: apps/v1
kind: Deployment
metadata:
  name: cve
  namespace: crates-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cve
  template:
    metadata:
      labels:
        app: cve
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: container-0
        image: localhost:30500/crates-pro-cve:local-20251024-0056
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_HOST_IP
          value: "postgresql-test1.postgresql.svc.cluster.local"
        - name: POSTGRES_HOST_PORT
          value: "5432"
        - name: KAFKA_BROKER
          value: "kafka.confluent.svc.cluster.local:9092"
        - name: TUGRAPH_BOLT_URL
          value: "bolt://tugraph-test1.tugraph.svc.cluster.local:7687"
        volumeMounts:
        - name: log-volume
          mountPath: /workdir/log
      volumes:
      - name: log-volume
        hostPath:
          path: /mnt/devops/log/cve
          type: DirectoryOrCreate
