[package]
name = "delta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diffs = { workspace = true }
thiserror = { workspace = true }
flate2 = { workspace = true, features = ["zlib"] }
rayon = { workspace = true }
[features]
default = ["diff_mydrs"]
diff_mydrs = []
